### ISSUE TITLE
specify which version of Leiningen Conjure is compatible with

### ISSUE THREAD

**Issue by uvtc** [macourtney/Conjure#3]
The getting-started guide should address lein version compatibility.

**Comment by macourtney** [comment]
I've added a mention of Leiningen 2.0. If you think that's good enough I will close this comment.

Also, the wiki is out of date. I'll try to update it as you find issues (or you can make the changes yourself). Please be patient with me.

**Comment by uvtc** [comment]
The getting-started wiki page indicates adding org.conjure/lein-conjure to both your project's `:profiles :dev :dependencies` as well as your ~/.lein/profiles.clj `:user :plugins`. Is that correct?

In my experience with lein plug-ins for creating projects (like the lein compojure plug-in), you don't need to add it to either place. You just go and attempt to use the plug-in, and lein takes care of fetching it (to make it available) and then runs it.

**Comment by uvtc** [comment]
That plug-in procedure (or lack thereof) I mention above is outlined here: https://github.com/weavejester/compojure/wiki/Getting-Started .

**Comment by macourtney** [comment]
I think that plugin procedure relies on a template which I have not
created for Conjure yet.

For some reason, the only way I could get Conjure to work was to add
the reference to both places. If I didn't only some of the commands
would work, but others wouldn't. If you figure out what's going on,
let me know. Otherwise, add Conjure to both your project file and your
profiles file.

-Matt Courtney

**Comment by uvtc** [comment]
Ok, thanks, Matt.

In that case, since the wiki now mentions lein 2, and the rest appears correct for now, closing this issue.
